#!/usr/bin/env bash

iscidr () {
    [[ ${1} =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\/?[0-9]{1,2}?$ ]] && echo $1
}

inet_ntoa () {
    [[ ${1} =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]] || return 255
    IFS=".";set - ${1};unset IFS
    local OCT1 OCT2 OCT3 OCT4
    OCT1=$(($1<<24));OCT2=$(($2<<16));OCT3=$(($3<<8));OCT4=$4
    echo $(($OCT1+$OCT2+$OCT3+$OCT4))
}

inet_aton () {
    [[ ${1} =~ ^[0-9]+$ ]] || return 255
    ADDRESS=${1}
    OCT4=$((${ADDRESS} % 256));ADDRESS=$((${ADDRESS}-${OCT4}));ADDRESS=$((${ADDRESS}/256))
    OCT3=$((${ADDRESS} % 256));ADDRESS=$((${ADDRESS}-${OCT3}));ADDRESS=$((${ADDRESS}/256))
    OCT2=$((${ADDRESS} % 256));ADDRESS=$((${ADDRESS}-${OCT2}));ADDRESS=$((${ADDRESS}/256))
    OCT1=$((${ADDRESS} % 256))
    echo "${OCT1}.${OCT2}.${OCT3}.${OCT4}"
}

function debug_http () {
    curl -s $@ -o /dev/null \
    -w "http_code %{http_code} time_appconnect %{time_appconnect} time_namelookup %{time_namelookup} time_connect %{time_connect} time_pretransfer %{time_pretransfer} time_starttransfer %{time_starttransfer} time_total %{time_total} speed_download %{speed_download}\n"
}

function debug_http_csv() {
    echo "timestamp;http_code;time_appconnect;time_namelookup;time_connect;time_pretransfer;time_starttransfer;time_total;speed_download"
    for ((i=0;$i<=$2;i++)) {
        curl -s $1 -o /dev/null -w "$(date +%s);%{http_code};%{time_appconnect};%{time_namelookup};%{time_connect};%{time_pretransfer};%{time_starttransfer};%{time_total};%{speed_download}\n"
        sleep 1
    }
}
